addu-workspaces-path: ~/.addu/workspaces
supported-editors:
  - pycharm-community
  - pycharm-professional
  - vscode
  - None
ros-distros:
  noetic:
    - osrf/ros:noetic-desktop-full
    - ros:noetic-ros-base
  humble:
    - osrf/ros:humble-desktop-full
    - ros:humble-ros-base
